name: wikidata status
on:
  push:
    branches:
      - main
jobs:
  wikidata-info:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: install pandas
      run: pip3 install pandas
    - name: load data and report fillrate
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
        
          import pandas
          import pathlib
          
          df = pandas.read_csv(pathlib.Path.cwd() / 'entries.csv')
          wd = df.loc[df.wikidata.str.contains('Q', na=False)]
          ratio = round((len(wd)/len(df))*100, 1)
          
          print(len(wd), 'of', len(df), 'films have wikidata ids:', ratio, '%')
          


