name: wikidata status
on:
  push:
    branches:
      - main
jobs:
  wikidata-info:
    runs-on: ubuntu-latest 
    env: 
      CI_COMMIT_MESSAGE: action run
    permissions:
      contents: write  
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
#    - name: install requirements
#      run: pip3 install -r requirements.txt
#    - name: run script
#      run: ./run.sh
    - name: load data and report fillrate
      uses: jannekem/run-python-script-action@v1
      with:
        script: |

          import pathlib
          print(pathlib.Path.cwd())

    - name: directory contents
      run: ls -al
#    - name: push repo
#      run: |
#        git config user.name 'github-actions[bot]'
#        git config user.email 'github-actions[bot]@users.noreply.github.com'
#        git add notebooks/
#        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
#        git push
        
